name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
    - name: Set VCPKG_ROOT
      run: echo "VCPKG_ROOT=$(pwd)/vcpkg" >> $GITHUB_ENV
    - name: Install dependencies
      run: make deps
    - name: Build and Test
      run: make all
